name: Feature Request
description: Suggest a new feature or improvement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a feature! Help us understand what you need and why.
  
  - type: textarea
    id: current-state
    attributes:
      label: Current situation
      description: Describe how things work right now (or what's missing)
      placeholder: "Right now, when I want to do X, I have to..."
    validations:
      required: true
  
  - type: textarea
    id: problem
    attributes:
      label: Why this matters
      description: What problem does this create? Why is it frustrating or limiting?
      placeholder: "This is frustrating because..."
    validations:
      required: true
  
  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed solution
      description: What should happen instead? Describe the feature you'd like to see.
      placeholder: "This project should..."
    validations:
      required: true
  
  - type: textarea
    id: workarounds
    attributes:
      label: Current workarounds
      description: Are there ways to accomplish this today, even if they're not ideal?
      placeholder: "I can work around this by..."
    validations:
      required: false
  
  - type: textarea
    id: alternatives
    attributes:
      label: Alternative solutions
      description: Have you considered other approaches that might solve this problem?
      placeholder: "Another way to solve this might be..."
    validations:
      required: false
  
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Anything else we should know? Screenshots, mockups, links to similar features?
    validations:
      required: false
